name: TestDriver.ai

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    name: "TestDriver"
    runs-on: ubuntu-latest
    steps:
      - uses: dashcamio/testdriver@main
        id: testdriver
        with:
          prompt: |
            2. click "Continue"
            2. focus the Wave input with the keyboard shorcut Command + I
            3. type 'ls' into the input
            4. press return
            5. validate Wave shows the result of 'ls'
      # - name: Send custom JSON data to Slack workflow
      #   id: slack
      #   if: ${{ always() }}
      #   uses: slackapi/slack-github-action@v1.25.0
      #   with:
      #     # This data can be any valid JSON from a previous step in the GitHub Action
      #     payload: |
      #       {
      #         "link": "${{ steps.testdriver.outputs.link }}",
      #         "summary": ${{ toJSON(steps.testdriver.outputs.summary)}}
      #       }
      #   env:
      #     SLACK_WEBHOOK_URL: "https://hooks.slack.com/triggers/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"
